### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by Jenson66** [tklengyel/honeybrid#3]
Why I get this error “there is no such file or directory”, after execute "./build"。

**Comment by tklengyel** [comment]
There is no `build.sh` anymore, just do `./autogen.sh && ./configure && make`

**Comment by Jenson66** [comment]
yeah,but after execute "make", follow the http://honeybrid.sf.net step, I get another error 
![image](https://user-images.githubusercontent.com/37404833/50807644-10a63300-1336-11e9-9f52-a48e6d7fe88c.png)
source code from http://honeybrid.sf.net.
thank you.

**Comment by Jenson66** [comment]
> yeah,but after execute "make", follow the http://honeybrid.sf.net step, I get another error
> ![image](https://user-images.githubusercontent.com/37404833/50807644-10a63300-1336-11e9-9f52-a48e6d7fe88c.png)
> source code from http://honeybrid.sf.net.
> thank you.

**Comment by zhanz5** [comment]
> There is no `build.sh` anymore, just do `./autogen.sh && ./configure && make`

yeah,but after execute "make", follow the http://honeybrid.sf.net step, I get another error
![image](https://user-images.githubusercontent.com/37404833/50807770-87433080-1336-11e9-90ba-c5d79ec58f0d.png)
source code from http://honeybrid.sf.net.
thank you.

**Comment by K0zero** [comment]
> > There is no `build.sh` anymore, just do `./autogen.sh && ./configure && make`
> 
> yeah,but after execute "make", follow the http://honeybrid.sf.net step, I get another error ![image](https://user-images.githubusercontent.com/37404833/50807770-87433080-1336-11e9-90ba-c5d79ec58f0d.png) source code from http://honeybrid.sf.net. thank you.

well, I also have the same problem. did you have some ideas of solving this problem?
